-- Create the database
CREATE DATABASE tshirt_store;

-- Use the database
USE tshirt_store;

-- Create the t-shirts table
CREATE TABLE tshirts (
    tshirt_id INT PRIMARY KEY AUTO_INCREMENT,
    brand VARCHAR(50),
    color VARCHAR(20),
    size VARCHAR(10),
    price DECIMAL(10, 2),
    stock_quantity INT
);

-- Create the discount table
CREATE TABLE discounts (
    discount_id INT PRIMARY KEY AUTO_INCREMENT,
    tshirt_id INT,
    discount_percentage DECIMAL(5, 2),
    FOREIGN KEY (tshirt_id) REFERENCES tshirts(tshirt_id)
);

-- Insert 100 t-shirts into the table with random values
INSERT INTO tshirts (brand, color, size, price, stock_quantity)
SELECT
    ELT(FLOOR(1 + RAND() * 4), 'adidas', 'nike', 'puma', 'skechers') AS brand,
    ELT(FLOOR(1 + RAND() * 4), 'red', 'blue', 'black', 'white') AS color,
    ELT(FLOOR(1 + RAND() * 5), 'xs', 's', 'm', 'l', 'xl') AS size,
    ROUND(10 + (RAND() * (100 - 10)), 2) AS price,
    FLOOR(10 + (RAND() * (200 - 10))) AS stock_quantity
FROM
    (SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION
     SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10 UNION
     SELECT 11 UNION SELECT 12 UNION SELECT 13 UNION SELECT 14 UNION SELECT 15 UNION
     SELECT 16 UNION SELECT 17 UNION SELECT 18 UNION SELECT 19 UNION SELECT 20 UNION
     SELECT 21 UNION SELECT 22 UNION SELECT 23 UNION SELECT 24 UNION SELECT 25 UNION
     SELECT 26 UNION SELECT 27 UNION SELECT 28 UNION SELECT 29 UNION SELECT 30 UNION
     SELECT 31 UNION SELECT 32 UNION SELECT 33 UNION SELECT 34 UNION SELECT 35 UNION
     SELECT 36 UNION SELECT 37 UNION SELECT 38 UNION SELECT 39 UNION SELECT 40 UNION
     SELECT 41 UNION SELECT 42 UNION SELECT 43 UNION SELECT 44 UNION SELECT 45 UNION
     SELECT 46 UNION SELECT 47 UNION SELECT 48 UNION SELECT 49 UNION SELECT 50 UNION
     SELECT 51 UNION SELECT 52 UNION SELECT 53 UNION SELECT 54 UNION SELECT 55 UNION
     SELECT 56 UNION SELECT 57 UNION SELECT 58 UNION SELECT 59 UNION SELECT 60 UNION
     SELECT 61 UNION SELECT 62 UNION SELECT 63 UNION SELECT 64 UNION SELECT 65 UNION
     SELECT 66 UNION SELECT 67 UNION SELECT 68 UNION SELECT 69 UNION SELECT 70 UNION
     SELECT 71 UNION SELECT 72 UNION SELECT 73 UNION SELECT 74 UNION SELECT 75 UNION
     SELECT 76 UNION SELECT 77 UNION SELECT 78 UNION SELECT 79 UNION SELECT 80 UNION
     SELECT 81 UNION SELECT 82 UNION SELECT 83 UNION SELECT 84 UNION SELECT 85 UNION
     SELECT 86 UNION SELECT 87 UNION SELECT 88 UNION SELECT 89 UNION SELECT 90 UNION
     SELECT 91 UNION SELECT 92 UNION SELECT 93 UNION SELECT 94 UNION SELECT 95 UNION
     SELECT 96 UNION SELECT 97 UNION SELECT 98 UNION SELECT 99 UNION SELECT 100) AS numbers;

-- Insert discounts for the first 10 t-shirts
INSERT INTO discounts (tshirt_id, discount_percentage)
SELECT tshirt_id, ROUND(5 + (RAND() * (30 - 5)), 2)
FROM tshirts
WHERE tshirt_id <= 10;

-- Select all t-shirts to verify
SELECT * FROM tshirts;

-- Select all discounts to verify
SELECT * FROM discounts;
